### ISSUE TITLE
Support publishing to crates.io

### ISSUE THREAD

**Issue by calixteman** [mozilla/task-boot#111]
It could be useful for rust based projects.
For reference:
https://doc.rust-lang.org/cargo/reference/publishing.html

**Comment by La0** [comment]
Is there a way to publish on crates.io without cargo ? Ideally an API that we could use from Python.

**Comment by Luni-4** [comment]
Closed in favor of #160

**Comment by marco-c** [comment]
When we have two duplicate issues we usually close the newest (not worth changing now, just mentioning it for the future).

**Comment by Luni-4** [comment]
Sorry, I didn't know that :P
