### ISSUE TITLE
Support multiple tags on push-artifact

### ISSUE THREAD

**Issue by La0** [mozilla/task-boot#42]
An image with multiple tags seems to only have the first tag published on a repository (that's the case with code-review)

**Comment by marco-c** [comment]
See also #39.

**Comment by La0** [comment]
This [should already be supported](https://github.com/mozilla/task-boot/blob/master/taskboot/docker.py#L165) when snot using `custom_tag`, which is the default in `push-artifacts`

But the code-review docker image produced by taskboot has only one repo (where i request 2):

Here is the extracted `manifest.json`, missing a `mozilla/code-review:testing` image name :

```
[{'Config': 'blobs/sha256/000e00461ca457fa849767a866355940881c6969122613bfaf6d6e058ba6d54e',
  'Layers': ['blobs/sha256/e7c96db7181be991f19a9fb6975cdbbd73c65f4a2681348e63a141a2192a5f10',
             'blobs/sha256/799a5534f213d4fa33305a25e1987f38be3dc015267400efab141fb1ee9071e0',
             'blobs/sha256/913b50bbe755394b4d4bb87d1e2fee5bb63dc41a1059a59e4f98c13446ff3e58',
             'blobs/sha256/11154abc60811ff7350dfd0101213f864a1fbd34c85b60a5b7a951417d380cb2',
             'blobs/sha256/c805e63f69fecabe254d2c108a81fcd5bb8557c8e6bbcb8f3c6a99157b36a7dd',
             'blobs/sha256/3f67adc04cd6f644612ccb406aec96fb007615e255c398fdac557a217a5c68fc',
             'blobs/sha256/6f9cd7ea0a4b70cf32ea485c07642707b54ba839922ee12f00382fddca4134df'],
  'RepoTags': ['registry.hub.docker.com/mozilla/code-review:850e1d52994ee6789dbddd98f02ecc4bcfb60e73']}]
```

**Comment by La0** [comment]
It works: `mozilla/code-review:testing` image  is now available after using that version: https://hub.docker.com/r/mozilla/code-review/tags
