### ISSUE TITLE
Revisit dind support

### ISSUE THREAD

**Issue by La0** [mozilla/task-boot#86]
As it seems to be able to build code-review bot image: https://github.com/mozilla/code-review/pull/266

**Comment by La0** [comment]
[Here is a task](https://community-tc.services.mozilla.com/tasks/QVWQitBmQ3G6NGTzxrWHsg/runs/0/logs/https%3A%2F%2Fcommunity-tc.services.mozilla.com%2Fapi%2Fqueue%2Fv1%2Ftask%2FQVWQitBmQ3G6NGTzxrWHsg%2Fruns%2F0%2Fartifacts%2Fpublic%2Flogs%2Flive.log) where the code-review bot docker image was built using taskcluster dind, using [taskgraph](https://hg.mozilla.org/ci/taskgraph) base image - instead of taskboot.

Several steps are accomplished here:
1. checkout of the target repo (we already have that)
2. docker build + tag on the remote docker daemon (we need that)
3. docker squash (we don't need that)
4. docker image download & compression with zstandard to publish as an artifact (we need that)

Build is accomplished by a custom made docker client ([high level workflow](https://hg.mozilla.org/ci/taskgraph/file/tip/src/taskgraph/docker.py#l101) & [low level implem](https://hg.mozilla.org/ci/taskgraph/file/tip/src/taskgraph/util/docker.py#l37)):
1. a docker image full tag is created
2. a TAR archive is built with the docker context with `docker.stream_context_tar` - this method can be simplified a lot for us, as we don't need the extra commands support
3. that archive is sent to the docker daemon (through the unix socket) on `/build` endpoint with `docker.post_to_docker`

At that point, the image is stored on the docker daemon side, we need to get it back in the task, so that an artifact can be published. Releng does that with an external script [download-and-compress](https://hg.mozilla.org/ci/taskgraph/file/tip/taskcluster/docker/image_builder/download-and-compress) which does the following:
0. (in a retry loop)
1. Download the tagged image from the unix socket endpoint `/images/<image:hash>/get` in a stream (with requests)
2. compress inline with python's zstandard

I created [a test task](https://firefox-ci-tc.services.mozilla.com/tasks/OAda1tyzT2a0EJdFVZywVw/runs/0/logs/https%3A%2F%2Ffirefox-ci-tc.services.mozilla.com%2Fapi%2Fqueue%2Fv1%2Ftask%2FOAda1tyzT2a0EJdFVZywVw%2Fruns%2F0%2Fartifacts%2Fpublic%2Flogs%2Flive.log) on the firefox-ci instance to check the dind docker daemon version: [it's still 1.18](https://docs.docker.com/engine/api/v1.18/) - aka the currently oldest "supported" version of docker api. 

The last docker-py version compatible might be [2.7.0](https://github.com/docker/docker-py/releases/tag/2.7.0) as [1.21 is the minimum for 3.0.0](https://github.com/docker/docker-py/releases/tag/3.0.0)

**Comment by La0** [comment]
[docker-py==2.7.0](https://firefox-ci-tc.services.mozilla.com/tasks/Fr3gNu8vTGmO1r3R_R9DsA/runs/0/logs/https%3A%2F%2Ffirefox-ci-tc.services.mozilla.com%2Fapi%2Fqueue%2Fv1%2Ftask%2FFr3gNu8vTGmO1r3R_R9DsA%2Fruns%2F0%2Fartifacts%2Fpublic%2Flogs%2Flive.log) does not work :'(

**Comment by tomprince** [comment]
You could directly use the image mentioned [here](https://hg.mozilla.org/ci/taskgraph/file/tip/src/taskgraph/transforms/docker_image.py#l27), which has taskgraph built-in. You can see an example task using it [here](https://firefox-ci-tc.services.mozilla.com/tasks/MQHF0XcWR3KwsFUgFfh0UQ).

**Comment by La0** [comment]
Thanks @tomprince, i'm aware since you've submitted https://github.com/mozilla/code-review/pull/266 to do that.
We use task-boot on several of our projects, and I'd personally prefer to continue using it over taskgraph which seems pretty overkill simply to build a docker image.

**Comment by tomprince** [comment]
It is designed to be used with taskgraph, but I could be used without using the rest of taskgraph (although it *is* slightly opinionated about where it expects files).

**Comment by La0** [comment]
I got DinD support working in this PR #115 

I'm now able to build a docker image with `dind: true` and then run it with `task-image` in the same group.

Once that lands, i'll release a new version and use that on Relman Analysis projects
